#!/bin/bash

# With disk mounted adding an image to an SD card
# sudo diskutil partitionDisk /dev/diskXX 1 MBR "Free Space" %noformat% 100%
# sudo dd bs=1m if=XXX.img of=/dev/diskXX

# Update Firmware
sudo rpi-update
sudo reboot

# Update Software
sudo apt-get update -y
sudo apt-get upgrade -y

# Setup new user
sudo adduser phil
sudo adduser phil pi 
sudo adduser phil sudo
sudo mkdir /home/phil/.ssh
sudo touch /home/phil/authorized_keys

# Now logoff
cat ~/.ssh/id_rsa.pub | ssh phil@raspberrypi 'cat >> .ssh/authorized_keys'

# Install apps
sudo apt-get install screen -y
sudo apt-get install emacs -y
sudo apt-get install apache2 -y
sudo apt-get install mysql -y


